on:   #trigger workflow when ?
  push:  
    branches: 
      - main
      - "release/**"
    paths:
      - "src/**"  
on:   #trigger workflow when ?
  pull:  
    branches: 
      - main
      - "release/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
      - name: run tests
        run: npm test  


